apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - networkpolicy.yaml
  - configmap.yaml
  - api-deployment.yaml
  - api-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: secureops
  app.kubernetes.io/managed-by: kustomize
