apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: secureops-dev
namePrefix: dev-

resources:
  - ../../base

replicas:
  - name: secureops-api
    count: 1
  - name: secureops-web
    count: 1

patches:
  - target:
      kind: ConfigMap
      name: secureops-config
    patch: |-
      - op: replace
        path: /data/ASPNETCORE_ENVIRONMENT
        value: "Development"
